import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, GraduationCap, HandHeart, Headphones, PackageCheck, PencilRuler, ShieldCheck, Store, Users } from "lucide-react";
import { bookSubcategories, departments, productsByDepartment, stationerySubcategories } from "@/data/catalog";
import { ProductGrid } from "@/components/product-grid";
import { NewsletterForm } from "@/components/newsletter-form";

const bookProducts=productsByDepartment("books");
const stationeryProducts=productsByDepartment("stationery");

export default function Home() {
  return <>
    <section className="home-hero"><div className="hero-inner"><Image src="/images/hero-stationery-v2.png" alt="School stationery, books, art supplies and gifts" fill priority sizes="100vw" /><div className="shell hero-copy"><h1>Everything for school,<br />creativity & gifting</h1><p>Enter through Books or Stationery, then browse the exact subcategory and products you need.</p><div className="hero-actions"><Link className="button primary" href="/stationery">Shop stationery <PencilRuler size={18} /></Link><Link className="button secondary" href="/books">Browse books <BookOpen size={18} /></Link></div><div className="hero-notes"><span><GraduationCap /><b>For Every Learner<small>School • College • Life</small></b></span><span><Users /><b>Trusted by Families<small>In Our Community</small></b></span><span><HandHeart /><b>Small Store, Big Support</b></span></div></div></div></section>
    <section className="section department-choice" id="departments"><div className="shell"><div className="section-head"><div><span className="kicker">Start shopping</span><h2>Choose a department</h2><p>Books and Stationery have their own subcategories and product collections.</p></div></div><div className="department-grid">{departments.map((department,index)=><Link className={`department-card ${department.slug}`} href={`/${department.slug}`} key={department.slug}><div><span>{index===0?<BookOpen/>:<PencilRuler/>}</span><small>Vidyarthi</small><h2>{department.name}</h2><p>{department.short}</p><b>Enter {department.name} <ArrowRight/></b></div><Image src={department.image} alt="" width={420} height={300}/></Link>)}</div></div></section>
    <section className="section soft-section home-department-section"><div className="shell"><div className="section-head"><div><span className="kicker">Books department</span><h2>Browse books by subcategory</h2><p>School learning, exam preparation, reference and reading.</p></div><Link href="/books">View all books <ArrowRight /></Link></div><div className="home-subcategory-row">{bookSubcategories.map(category=><Link href={`/books/${category.slug}`} key={category.slug}><Image src={category.image} alt="" width={90} height={80}/><span><strong>{category.name}</strong><small>{category.short}</small></span><ArrowRight/></Link>)}</div><ProductGrid products={bookProducts.slice(0,4)} className="featured-grid department-product-grid" /></div></section>
    <section className="section home-department-section"><div className="shell"><div className="section-head"><div><span className="kicker">Stationery department</span><h2>Browse stationery by subcategory</h2><p>Writing, school, art, office, notebooks and gifting.</p></div><Link href="/stationery">View all stationery <ArrowRight /></Link></div><div className="home-subcategory-row stationery">{stationerySubcategories.map(category=><Link href={`/stationery/${category.slug}`} key={category.slug}><Image src={category.image} alt="" width={90} height={80}/><span><strong>{category.name}</strong><small>{category.short}</small></span><ArrowRight/></Link>)}</div><ProductGrid products={stationeryProducts.slice(0,4)} className="featured-grid department-product-grid" /></div></section>
    <section className="benefit-strip"><div className="shell benefits"><div><ShieldCheck /><span><strong>Secure Payments</strong><small>100% safe and encrypted</small></span></div><div><Store /><span><strong>Store Pickup Available</strong><small>Order online, pick up at our store</small></span></div><div><PackageCheck /><span><strong>Quality Products</strong><small>Carefully sourced for students & creators</small></span></div><div><Headphones /><span><strong>Helpful Support</strong><small>We’re here to help</small></span></div></div></section>
    <section className="section"><div className="shell promo-grid"><Link className="promo-card promo-school" href="/stationery/school-essentials"><span>School-ready savings</span><h2>Pack the essentials.<br />Start the day bright.</h2><p>Bags, bottles, notebooks and everyday classroom favourites.</p><b>Shop school essentials <ArrowRight /></b></Link><Link className="promo-card promo-gifts" href="/stationery/gifts-return-gifts"><span>Celebrate together</span><h2>Easy return gifts<br />for every little party.</h2><p>Browse cheerful, ready-to-share gifts for groups of every size.</p><b>Explore gifts <ArrowRight /></b></Link></div></section>
    <section className="newsletter"><div className="shell newsletter-inner"><div><span className="kicker">Stay in the loop</span><h2>New arrivals, school lists and special offers.</h2><p>Join our updates and be the first to know what is new in store.</p></div><NewsletterForm /></div></section>
  </>;
}
