"use client";
import Link from "next/link";
import { CheckCircle2, ImagePlus, Save, UploadCloud } from "lucide-react";
import { FormEvent, useState } from "react";
import { AdminShell } from "./admin-shell";

export type AdminField = { label: string; name: string; type?: "text" | "number" | "textarea" | "select" | "date" | "time" | "file" | "checkbox"; placeholder?: string; value?: string; options?: string[]; full?: boolean; help?: string };
export type AdminFormSection = { title: string; description?: string; fields: AdminField[] };

export function AdminForm({ title, description, sections, backHref, submitLabel = "Save changes" }: { title: string; description: string; sections: AdminFormSection[]; backHref: string; submitLabel?: string }) {
  const [saved, setSaved] = useState(false);
  const [files, setFiles] = useState<string[]>([]);
  function submit(event: FormEvent) { event.preventDefault(); setSaved(true); window.scrollTo({ top: 0, behavior: "smooth" }); }
  return <AdminShell title={title} description={description}><form className="admin-form-layout" onSubmit={submit}><div className="admin-form-main">{saved && <div className="demo-success"><CheckCircle2 /><span><strong>Preview saved successfully</strong><small>This static form demonstrates the final admin workflow. Backend storage will be connected later.</small></span></div>}{sections.map((section) => <section className="admin-panel form-panel" key={section.title}><div className="panel-heading"><h2>{section.title}</h2>{section.description && <p>{section.description}</p>}</div><div className="admin-form-grid">{section.fields.map((field) => <label className={`${field.full ? "full" : ""} ${field.type === "checkbox" ? "check-field" : ""}`} key={field.name}>{field.type === "checkbox" ? <><input type="checkbox" defaultChecked={field.value === "true"} /><span><strong>{field.label}</strong>{field.help && <small>{field.help}</small>}</span></> : <><span>{field.label}</span>{field.type === "textarea" ? <textarea name={field.name} defaultValue={field.value} placeholder={field.placeholder} rows={5} /> : field.type === "select" ? <select name={field.name} defaultValue={field.value}>{field.options?.map((option) => <option key={option}>{option}</option>)}</select> : field.type === "file" ? <div className="file-drop"><ImagePlus /><strong>Choose images or drag them here</strong><small>JPG, PNG or WebP • up to 10 images</small><input type="file" multiple onChange={(event) => setFiles(Array.from(event.target.files || []).map((file) => file.name))} /></div> : <input name={field.name} type={field.type || "text"} defaultValue={field.value} placeholder={field.placeholder} />}{field.help && <small>{field.help}</small>}{field.type === "file" && files.length > 0 && <div className="file-list"><UploadCloud /> {files.join(", ")}</div>}</>}</label>)}</div></section>)}</div><aside className="admin-save-card"><h3>Ready to publish?</h3><p>Review the details, visibility and pricing before saving this preview.</p><button className="button primary" type="submit"><Save /> {submitLabel}</button><Link className="button secondary" href={backHref}>Cancel</Link><small>No database changes are made in this static frontend.</small></aside></form></AdminShell>;
}
