"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ProductGrid } from "./product-grid";
import type { Product } from "@/data/catalog";

export function CatalogPage({ title, description, items }: { title: string; description: string; items: Product[] }) {
  const [offers,setOffers]=useState(false); const [price,setPrice]=useState("all"); const [rating,setRating]=useState(0); const [sort,setSort]=useState("popular");
  const visible=useMemo(()=>{const result=items.filter(product=>(!offers||!!product.badge)&&(price==="all"||(price==="under250"&&product.price<250)||(price==="250to500"&&product.price>=250&&product.price<=500)||(price==="over500"&&product.price>500))&&product.rating>=rating);return [...result].sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:sort==="new"?b.slug.localeCompare(a.slug):b.reviews-a.reviews)},[items,offers,price,rating,sort]);
  return <><section className="page-hero"><div className="shell"><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><span>{title}</span></div><h1>{title}</h1><p>{description}</p></div></section><section className="section"><div className="shell catalog-layout"><aside className="filters"><div className="filter-block"><h3>Availability</h3><label><input type="checkbox" defaultChecked /> In stock</label><label><input type="checkbox" checked={offers} onChange={e=>setOffers(e.target.checked)} /> Special offers</label></div><div className="filter-block"><h3>Price</h3><label><input type="radio" name="price" checked={price==="all"} onChange={()=>setPrice("all")} /> All prices</label><label><input type="radio" name="price" checked={price==="under250"} onChange={()=>setPrice("under250")} /> Under ₹250</label><label><input type="radio" name="price" checked={price==="250to500"} onChange={()=>setPrice("250to500")} /> ₹250–₹500</label><label><input type="radio" name="price" checked={price==="over500"} onChange={()=>setPrice("over500")} /> Above ₹500</label></div><div className="filter-block"><h3>Customer rating</h3><label><input type="radio" name="rating" checked={rating===4} onChange={()=>setRating(4)} /> 4 stars and above</label><label><input type="radio" name="rating" checked={rating===0} onChange={()=>setRating(0)} /> Any rating</label></div><button className="clear-filters" onClick={()=>{setOffers(false);setPrice("all");setRating(0)}}>Clear filters</button></aside><div><div className="catalog-top"><span>{visible.length} products</span><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Sort: Popularity</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option><option value="new">Newest first</option></select></div>{visible.length?<ProductGrid products={visible}/>:<div className="empty-state small-empty"><h2>No products match these filters.</h2><p>Clear the filters to see the complete collection.</p><button className="button primary" onClick={()=>{setOffers(false);setPrice("all");setRating(0)}}>Clear filters</button></div>}</div></div></section></>;
}
