"use client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Check, Heart, Minus, Plus, ShieldCheck, ShoppingCart, Star, Store, Truck } from "lucide-react";
import { useState } from "react";
import { formatPrice, type Product } from "@/data/catalog";
import { useShop } from "./shop-provider";

export function ProductDetail({ product }: { product: Product }) {
  const [quantity, setQuantity] = useState(1); const { addToCart, toggleWishlist, wishlist } = useShop(); const router = useRouter(); const saved = wishlist.includes(product.slug); const discount = Math.round((1 - product.price / product.mrp) * 100);
  function buyNow() { addToCart(product, quantity); router.push("/checkout"); }
  return <><section className="product-page section"><div className="shell"><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href={`/${product.department}`}>{product.departmentName}</Link><span>/</span><Link href={`/${product.department}/${product.subcategorySlug}`}>{product.subcategory}</Link><span>/</span><span>{product.name}</span></div><div className="product-detail"><div className="product-gallery"><div className="main-product-image"><Image src={product.image} alt={product.name} fill priority sizes="(max-width: 800px) 100vw, 50vw" /></div><div className="thumb-row">{[1,2,3].map((item) => <button aria-label={`View product image ${item}`} className={item === 1 ? "active" : ""} key={item}><Image src={product.image} alt="" width={90} height={90} /></button>)}</div></div><div className="product-summary"><span className="product-category">{product.category}</span><h1>{product.name}</h1><div className="detail-rating"><span><Star fill="currentColor" /> {product.rating}</span><b>{product.reviews} reviews</b></div><p className="product-short">{product.short}</p><div className="detail-price"><strong>{formatPrice(product.price)}</strong><del>{formatPrice(product.mrp)}</del><span>Save {discount}%</span></div><p className="tax-note">Inclusive of all taxes</p><div className="stock-line"><Check /> In stock and ready to order</div><div className="quantity-label">Quantity</div><div className="buy-row"><div className="qty-control"><button aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(1,quantity-1))}><Minus /></button><span>{quantity}</span><button aria-label="Increase quantity" onClick={() => setQuantity(quantity+1)}><Plus /></button></div><button className="button primary flex-button" onClick={() => addToCart(product,quantity)}><ShoppingCart /> Add to cart</button><button aria-label={saved ? "Remove from wishlist" : "Add to wishlist"} className={`detail-wish ${saved ? "saved" : ""}`} onClick={() => toggleWishlist(product.slug)}><Heart fill={saved ? "currentColor" : "none"} /></button></div><button className="button buy-now" onClick={buyNow}>Buy now</button><div className="service-cards"><div><Truck /><span><strong>Delivery</strong><small>Calculated at checkout</small></span></div><div><Store /><span><strong>Store pickup</strong><small>Collect when your order is ready</small></span></div><div><ShieldCheck /><span><strong>Secure checkout</strong><small>Protected payment experience</small></span></div></div></div></div></div></section><section className="section soft-section"><div className="shell details-grid"><div><span className="kicker">About this product</span><h2>Made for everyday learning and creativity.</h2><p>{product.description}</p></div><div className="spec-card"><h3>Product details</h3>{Object.entries(product.specs).map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section></>;
}
